name: Format JavaScript

on:
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest


    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: |
          npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply JavaScript formatting
          branch: ${{ github.head_ref }}